name: Custom Workflow Integration

on:
  push:
    branches:
      - main

jobs:
  custom-task:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run custom workflow task
        run: |
          chmod +x ./generate-release-notes.sh
          ./generate-release-notes.sh
