name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or any branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js (if needed for building the site)
        uses: actions/setup-node@v3
        with:
          node-version: "20" # use the node version compatible with your project

      - name: Install dependencies (if you have a build process that requires npm)
        run: npm install

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # the folder that you want to deploy
