name: Scheduled Maintenance Tasks

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run maintenance script
        run: |
          chmod +x ./maintainance-script.sh
          ./maintainance-script.sh
